version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: buzzcircle-mysql
    environment:
      MYSQL_DATABASE: buzzcircle
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306" # maps container 3306 to host 3307
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: buzzcircle-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_USER: appuser
      DB_PASS: apppass

volumes:
  mysql-data:
